config/routes.rb
Rails.application.routes.draw do
  root 'friends#index'
  devise_for :users
  resources :friends
  get "home/about"=>"home#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index,:show]
  before_action :correct_user, only: [:edit,:update,:destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)
    @friends= current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "not Authenticate user for this friend" if @friend.nil?
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter,:user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, class:"form-control") do |form|  %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group my-2">
    <%= form.text_field :first_name ,class:"form-control",placeholder:"FIRST NAME"%>
  </div>

  <div class="form-group my-2">
    <%= form.text_field :last_name,class:"form-control" ,placeholder:"LAST NAME"%>
  </div>

  <div class="form-group my-2">
    <%= form.text_field :email,class:"form-control",placeholder:"EAMIL" %>
  </div>

  <div class="form-group my-2">
    <%= form.text_field :phone ,class:"form-control",placeholder:"MOBILE NO"%>
  </div>

  <div class="form-group my-2">
    <%= form.text_field :twitter ,class:"form-control",placeholder:"TWITTER USERNAME" %>
  </div>
  <%= form.number_field :user_id,
      id: :friend_user_id, class:"form-control",
      value: current_user.id,type: :hidden%>
  <div class="form-group my-3 ">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div class="card my-5 " style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= friend.first_name %> <%= friend.last_name %></h5>
    <p class="card-text">
      <%= friend.email %> || 
      <%= friend.phone %> ||
      <%= friend.twitter %>
    </p>
  </div>
</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show", @friend ,class:" btn btn-success"%> 
  <%= link_to "Delete", friend_path(@friend), 
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
            
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
<div id="friends">
  <table class="table table-striped table-bordered table-hover mt-5 shadow">
    <thead class="table-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Mobile No</th>
        <th>Twitter</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
          <tr>
            <td>
              <%= link_to "#{friend.first_name} #{friend.last_name}", friend, class:"link-underline-light"%>
            </td>
            <td><%= friend.email %></td>
            <td><%= friend.phone %></td>
            <td><%= friend.twitter %></td>
            <td>
              <%= link_to "Update", edit_friend_path(friend), class: "btn btn-secondary" %>
              <%= link_to "Delete", friend_path(friend), 
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Add Friend", new_friend_path, class: "btn btn-primary" %>
</div>
<% else %>
  <%= render "home/index" %>
<% end %>

app/views/friends/new.html.erb
<h1 class="text-center">Add Friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

<div>
  
  <%= link_to "Back to friends", friends_path,class:"btn btn-primary" %>
  </br></br>
  <%# <%= button_to "Destroy this friend", @friend, method: :delete ,class:"btn btn-danger" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Friend App", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "About us" , home_about_path, class:"nav-link"%>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to "Add Friend" , new_friend_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Show Friend" , friends_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "exit", destroy_user_session_path,class:"nav-link", method: :delete %>
        </li>
        <li class="nav-item">
            <%= link_to "Edit Profile" , edit_user_registration_path, class:"nav-link"%>
        </li>
        <% else %>
        <li class="nav-item">
            <%= link_to "Sign up" , new_user_registration_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Sign In" , new_user_session_path, class:"nav-link"%>
        </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/_index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/about.html.erb
<h1>about us page</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css">
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title>Hello, world!</title>
  </head>
  <body >
    <%= render 'home/header'%>
    <% if notice%>
    <div class="alert alert-success alert-dismissible fade show border border-rounded mx-5 my-3" role="alert">
      <strong><%= notice%></strong>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    
    <% end %>
    <div class="container">
    <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>